name: 👷 PR

env:
  PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: '1'

on:
  push:
    branches-ignore:
      - main
      - production
      - renovate/*
      - changeset-release/*
      - release/*

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: 🧹 Lint
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: fell-lucas/setup-pnpm-action@main
      - run: pnpm lint

  unitTests:
    name: 🧪 Unit Tests
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: fell-lucas/setup-pnpm-action@main
      - run: pnpm test:unit

  e2eTests:
    name: 🎭 E2E Tests
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: fell-lucas/setup-pnpm-action@main
      - run: curl -sSfL https://get.tur.so/install.sh | bash
      - run: echo "$HOME/.turso" >> $GITHUB_PATH
      - run: pnpm run test:integration
